[tool.poetry]
name = "codecrafters-http-server-python"
version = "0.1.0"
description = ""
authors = ["Marek Kubowicz <marek@kubowicz.pl>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
